sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.11"
branches:
  only:
    - master
notifications:
  email:
    - snowyu.lee@gmail.com
script: npm test

before_install:
  - npm install -g npm@latest

